/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.personas.vistas;

import gui.interfaces.IControladorPersonas;
import javax.swing.table.TableRowSorter;
import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Tuquina Fernando, Orellana Gonzalo
 */
public class Personas extends javax.swing.JDialog {

    private IControladorPersonas ca;
    
    /**
     * Creates new form Personas
     */
    public Personas(java.awt.Frame parent, boolean modal, IControladorPersonas ca) {
        super(parent, modal);
        initComponents();
        this.ca=ca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonNuevoAlumno = new javax.swing.JButton();
        BotonBorrarAlumno = new javax.swing.JButton();
        BotonModificarAlumno = new javax.swing.JButton();
        txtApellidosAlumno = new javax.swing.JTextField();
        BotonBuscarAlumno = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaAlumnos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BotonNuevoProfesor = new javax.swing.JButton();
        BotonBorrarProfesor = new javax.swing.JButton();
        BotonModificarProfesor = new javax.swing.JButton();
        txtApellidosProfesor = new javax.swing.JTextField();
        BotonBuscarProfesor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProfesores = new javax.swing.JTable();
        BotonVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Alumnos");

        BotonNuevoAlumno.setText("Nuevo");
        BotonNuevoAlumno.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Crea un nuevo alumno]</p> </body>  </html>");
        BotonNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoAlumnoActionPerformed(evt);
            }
        });

        BotonBorrarAlumno.setText("Borrar");
        BotonBorrarAlumno.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Borra un alumno seleccionado]</p> </body>  </html>");
        BotonBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarAlumnoActionPerformed(evt);
            }
        });

        BotonModificarAlumno.setText("Modificar");
        BotonModificarAlumno.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Modifica un alumno seleccionado]</p> </body>  </html>");
        BotonModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarAlumnoActionPerformed(evt);
            }
        });

        txtApellidosAlumno.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Ingrese sólo letras]</p> </body>  </html>");
        txtApellidosAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidosAlumnoPresionarTecla(evt);
            }
        });

        BotonBuscarAlumno.setText("Buscar");
        BotonBuscarAlumno.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[ENTER]</p> </body>  </html>");
        BotonBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarAlumnoActionPerformed(evt);
            }
        });

        TablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaAlumnos.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Tabla de Alumnos]</p> </body>  </html>");
        jScrollPane2.setViewportView(TablaAlumnos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Profesores");

        BotonNuevoProfesor.setText("Nuevo");
        BotonNuevoProfesor.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Crea un nuevo profesor]</p> </body>  </html>");
        BotonNuevoProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoProfesorActionPerformed(evt);
            }
        });

        BotonBorrarProfesor.setText("Borrar");
        BotonBorrarProfesor.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Borra un profesor seleccionado]</p> </body>  </html>");
        BotonBorrarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarProfesorActionPerformed(evt);
            }
        });

        BotonModificarProfesor.setText("Modificar");
        BotonModificarProfesor.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Modifica un profesor seleccionado]</p> </body>  </html>");
        BotonModificarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarProfesorActionPerformed(evt);
            }
        });

        txtApellidosProfesor.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Ingresar sólo texto]</p> </body>  </html>");
        txtApellidosProfesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidosProfesorKeyPressed(evt);
            }
        });

        BotonBuscarProfesor.setText("Buscar");
        BotonBuscarProfesor.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[ENTER]</p> </body>  </html>");
        BotonBuscarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarProfesorActionPerformed(evt);
            }
        });

        TablaProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaProfesores.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Tabla de profesores]</p> </body>  </html>");
        jScrollPane1.setViewportView(TablaProfesores);

        BotonVolver.setText("Volver");
        BotonVolver.setToolTipText("<html> <body bgcolor=\"white\"> <p width=\\\"100\"\\ style=\"color:#F14520\">[Regresa a la ventana principal]</p> </body>  </html>");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(BotonNuevoProfesor)
                        .addGap(18, 18, 18)
                        .addComponent(BotonBorrarProfesor)
                        .addGap(18, 18, 18)
                        .addComponent(BotonModificarProfesor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtApellidosProfesor)
                        .addGap(18, 18, 18)
                        .addComponent(BotonBuscarProfesor))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonNuevoAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(BotonBorrarAlumno)
                                .addGap(18, 18, 18)
                                .addComponent(BotonModificarAlumno)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtApellidosAlumno))
                        .addGap(18, 18, 18)
                        .addComponent(BotonBuscarAlumno))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonVolver)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevoAlumno)
                    .addComponent(BotonBorrarAlumno)
                    .addComponent(BotonModificarAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidosAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonNuevoProfesor)
                    .addComponent(BotonBorrarProfesor)
                    .addComponent(BotonModificarProfesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidosProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarProfesor))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoAlumnoActionPerformed
            this.ca.btnNuevoAlumnoClic(evt);
    }//GEN-LAST:event_BotonNuevoAlumnoActionPerformed

    private void BotonNuevoProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoProfesorActionPerformed
            this.ca.btnNuevoProfesorClic(evt);
    }//GEN-LAST:event_BotonNuevoProfesorActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
            this.ca.btnVolverClic(evt);
    }//GEN-LAST:event_BotonVolverActionPerformed

    private void BotonModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarAlumnoActionPerformed

            this.ca.btnModificarAlumnoClic(evt);
    }//GEN-LAST:event_BotonModificarAlumnoActionPerformed

    private void BotonModificarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarProfesorActionPerformed
  
            this.ca.btnModificarProfesorClic(evt);
    }//GEN-LAST:event_BotonModificarProfesorActionPerformed

    private void BotonBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarAlumnoActionPerformed
  
        this.ca.btnBuscarAlumnoClic(evt);
        
    }//GEN-LAST:event_BotonBuscarAlumnoActionPerformed

    private void txtApellidosProfesorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosProfesorKeyPressed
        this.ca.txtApellidosProfesorPresionarTecla(evt);
    }//GEN-LAST:event_txtApellidosProfesorKeyPressed

    private void txtApellidosAlumnoPresionarTecla(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosAlumnoPresionarTecla
        this.ca.txtApellidosAlumnoPresionarTecla(evt);
    }//GEN-LAST:event_txtApellidosAlumnoPresionarTecla

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.ca.ventanaGanaFoco(evt);
    }//GEN-LAST:event_formWindowGainedFocus

    private void BotonBuscarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarProfesorActionPerformed

      this.ca.btnBuscarProfesorClic(evt);
        
    }//GEN-LAST:event_BotonBuscarProfesorActionPerformed

    private void BotonBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarAlumnoActionPerformed

       this.ca.btnBorrarAlumnoClic(evt);
        
    }//GEN-LAST:event_BotonBorrarAlumnoActionPerformed

    private void BotonBorrarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarProfesorActionPerformed

        this.ca.btnBorrarProfesorClic(evt);
        
    }//GEN-LAST:event_BotonBorrarProfesorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("Ventana cerrada");        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrarAlumno;
    private javax.swing.JButton BotonBorrarProfesor;
    private javax.swing.JButton BotonBuscarAlumno;
    private javax.swing.JButton BotonBuscarProfesor;
    private javax.swing.JButton BotonModificarAlumno;
    private javax.swing.JButton BotonModificarProfesor;
    private javax.swing.JButton BotonNuevoAlumno;
    private javax.swing.JButton BotonNuevoProfesor;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JTable TablaAlumnos;
    private javax.swing.JTable TablaProfesores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtApellidosAlumno;
    private javax.swing.JTextField txtApellidosProfesor;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTablaAlumnos() {
        return TablaAlumnos;
    }

    public javax.swing.JTable getTablaProfesores() {
        return TablaProfesores;
    }

    public javax.swing.JTextField getjTextFieldAlumnos() {
        return txtApellidosAlumno;
    }

    public javax.swing.JTextField getjTextFieldProfesores() {
        return txtApellidosProfesor;
    }
    
    TableRowSorter trs;
    public TableRowSorter getTableRowSorter(){
            return this.trs;
    }
    
    
}
